### ISSUE TITLE
Control cycle and real time kernel

### ISSUE THREAD

**Issue by robograffitti** [ROBOTIS-GIT/ROBOTIS-THORMANG-MPC#30]
Does thormang 3 apply any real time patch such as PREEMPT_RT to assure its control cycle?

I do not find any description about it in the instruction of how to set up MPC.

**Comment by ROBOTIS-zerom** [comment]
THORMANG3 MPC just uses the generic kernel.

However, high priority is used.

See below:

- file : https://github.com/ROBOTIS-GIT/ROBOTIS-Framework/blob/master/robotis_controller/src/robotis_controller/robotis_controller.cpp
- function : void RobotisController::startTimer()

**Comment by robograffitti** [comment]
Thanks!

Now, I'm planning to apply hrpsys for OP3, so I was curious about how to handle real time issues for Thormang3.
