### ISSUE TITLE
Meaning of TWE

### ISSUE THREAD

**Issue by robograffitti** [ROBOTIS-GIT/ROBOTIS-THORMANG-MPC#31]
What does "TWE" means in the end of the name "ATIForceTorqueSensorTWE"?

**Comment by Jay-Song** [comment]
TWE is a shortened word of Transducer Without Electronics and the name of a version of ATI FT sensors.
This means that the sensor was provided without any electronic devices such as DAQ.

**Comment by Jay-Song** [comment]
> What does "TWE" means in the end of the name "ATIForceTorqueSensorTWE"?

TWE is a shortened word of Transducer Without Electronics and the name of a version of ATI FT sensors.
This means that the sensor was provided without any electronic devices such as DAQ.
