### ISSUE TITLE
Joint calibration

### ISSUE THREAD

**Issue by robograffitti** [ROBOTIS-GIT/ROBOTIS-THORMANG-MPC#32]
Is there any other way than offset_tuner?

There is an instruction of how to use thormang3_offset_tuner, but it does not provide any information about how our tuning is precise.

What is your standard measure of joint calibration?

**Comment by robograffitti** [comment]
In the case of HRP2, it moves each joint until hitting a corresponding limit pin for all joints.

If a robot has absolute encoders, it should have an alternative way for automatic joint calibration.

**Comment by robograffitti** [comment]
@robotpilot ping.

**Comment by kaym9n** [comment]
We just provide offset_tuner for joint calibration.
We will refer to your ideas when developing other platforms.
