### ISSUE TITLE
Why urg node is launched in MPC

### ISSUE THREAD

**Issue by robograffitti** [ROBOTIS-GIT/ROBOTIS-THORMANG-MPC#33]
When I was reading the code launching urg node, I found that it is launched in MPC.
https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-MPC/blob/master/thormang3_manager/launch/thormang3_manager.launch#L22

Why not in PPC?

**Comment by kaym9n** [comment]
At first we had run urg_node on PPC. 
In that case, It happened problems making pointcloud because TF was made in MPC, and lidar data was made in PPC. 
So we changed it into MPC.

**Comment by robograffitti** [comment]
Thanks for answering.

If possible, I'll try to think about an idea canceling the lidar topic communication between MPC and PPC.
