### ISSUE TITLE
Forward Kinematics giving wrong result

### ISSUE THREAD

**Issue by ghost** [ROBOTIS-GIT/ROBOTIS-THORMANG-MPC#9]
I have been working with a single arm and the forward, inverse kinematics were working correctly. I've recently assembled my dual arm robot with a torso frame connecting the torso motors to the shoulder motors (similar to the Thormang). After that the forward kinematics has been giving the wrong result because of which the end effector reaches a position different from the desired position. Do you have any idea how this might be happening?

Also, why have you added the offset and passive links in the data at the start of the ManipulatorKinematicsDynamics.cpp? 

Any help will be much appreciated. Thank you!

**Comment by s-changhyun** [comment]
I also have no idea about your happening.
As I told you before, we cannot support your debugging.

Also, you can ignore offset & passive links.
